import "./globals.css";
import type { Metadata } from "next";
import { Anonymous_Pro } from "next/font/google";

const anonymousPro = Anonymous_Pro({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={anonymousPro.className}>{children}</body>
    </html>
  );
}
